Bubble_sort algorithm
brytebee/bubble_sort pull request #1
Opened 2021-02-20 00:34 UTC by brytebee

> Do leave any necessary modification suggestions.

2021-02-20 00:49 UTC, mke2111 requested changes
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @brytebee, 👋🏽 
 **Thank you for the good job you got going on. The  method runs just fine and almost pass all test cases.**

## REQUIRED CHANGES

- [x] You have 1 rubocop offense detected locally.
- [x] Kindly add a brief description for this PR.
- [x] Kindly add a second method `bubble_sort_by` as required [in ordin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#assignment-1). See [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sortBy.png). So you need two methods.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-02-22 09:04 UTC, brytebee commented
I have effected the required changes. The Bubble_sort_by method is in a separate file.

2021-02-22 13:31 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Bright Atsighi** 
Nice job with the improvements for this project :muscle:  :muscle:
Your algorithms passes most of the tests :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] One of your methods is not working properly. Check out the expected behavior:
`bubble_sort_by(%w[functioning? is function this]) { |left, right| left.length - right.length } #expected this to be: ["is", "this", "function", "functioning?"]`
- [ ] Add a screenshot in your README file
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-23 04:22 UTC, bini-i requested changes
# Status: Changes Required :yellow_circle: 
### Hello  @brytebee :wave: 

### Thanks for working on the changes suggested. You have done a great job and your project passes most of the requirements, but you still can improve your project. 

- [ ] bubble_sory_by sorts an array in reverse order, Please make sure it sorts in ascending order.
THe following is the result I got as I run your code with examples provided [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/)
![Screenshot from 2021-02-23 07-19-19](https://user-images.githubusercontent.com/61377322/108801773-ab5e3c00-75a7-11eb-8602-074a2eaf2d35.png)
- [ ] and remove debugging instruction in committed code. Please refer to Inline comments.

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-02-23 04:22 UTC, bini-i commented on bubble_sort.rb
> +  puts swap
kindly remove debugging instructions as it is not related to the output of the function

2021-02-23 04:22 UTC, bini-i commented on bubble_sort_by.rb
> +  puts swap
Kindly remove debugging instructions as it is not related to the output of the function.

2021-02-23 08:27 UTC, mke2111 approved these changes
# **🎉 STATUS: APPROVED 🎉** 

## Hey @brytebee, 👋🏽 
 **Congratulations 🥳 🥂 . The methods run as expected.**

**You may now merge to the main branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-02-23 08:35 UTC, brytebee commented
Thank you.

2021-02-23 08:38 UTC, merged